services:

  web:
    build: .
    container_name: pi_2_sem_php_apache

    ports:
      - "8081:80"

    volumes:
      - ./app:/var/www/app
      - ./public:/var/www/public

    depends_on:
      - db


  db:
    image: mysql:8.0
    container_name: pi_2_sem_mysql_db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: OvmO8U2dHm2ywV8pTf8Vo0Bat
      MYSQL_DATABASE: playpark
      MYSQL_USER: admin
      MYSQL_PASSWORD: 8Z5tHHEF2F4TvEgrxdG1Dx0OK

    volumes:
      - ./mysql-data:/var/lib/mysql

    ports:
      - "3307:3306"


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pi_2_sem_phpmyadmin

    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

    ports:
      - "8889:80"

    depends_on:
      - db